:sparkles: feat: new cdn models, added migrations/
Tech-With-Tim/models pull request #3
Opened 2021-07-10 03:18 UTC by Correct-skill

2021-07-10 03:18 UTC, Correct-skill commented
The utils import still doesn't work for me, i dont know how to do it correctly, when i did `from .. import utils` it works, check that by running it locally

2021-07-10 03:37 UTC, SylteA requested changes

2021-07-10 03:37 UTC, SylteA commented on cdn/__init__.py
> +__all__ = [
tuple please

2021-07-10 03:37 UTC, SylteA commented on cdn/__init__.py
> +    "Asset",
don't use strings please

2021-07-10 03:37 UTC, SylteA commented on cdn/asset.py
> +    creator_id = Column(types.Integer(big=True))
foreign key

2021-07-10 03:37 UTC, SylteA commented on cdn/asset.py
> +        return cls(
please fetch record first,
then return `cls(**record)`

2021-07-10 03:37 UTC, SylteA commented on cdn/asset.py
> +            args.append(value)
you don't increment `i`

2021-07-10 03:37 UTC, SylteA commented on cdn/asset.py
> +            args.append(value)
you don't increment `i`

2021-07-10 03:37 UTC, SylteA commented on challenges/__init__.py
> +__all__ = [
tuple please

2021-07-10 03:37 UTC, SylteA commented on challenges/__init__.py
> +    "Challenge",
no need for string

2021-07-10 03:37 UTC, SylteA commented on migrations/0001_init_schema.down.sql
> +DROP FUNCTION IF EXISTS create_snowflake();
does this work with the `()`

2021-07-10 03:37 UTC, SylteA commented on migrations/0001_init_schema.down.sql
> +DROP FUNCTION IF EXISTS snowflake_to_timestamp(flake BIGINT);
does this work with the `(flake BIGINT)`

2021-07-10 03:37 UTC, SylteA commented on users/__init__.py
> +__all__ = [
tuple please

2021-07-10 03:37 UTC, SylteA commented on users/__init__.py
> +    "User",
no string

2021-07-10 03:49 UTC, Correct-skill commented on migrations/0001_init_schema.down.sql
> +DROP FUNCTION IF EXISTS create_snowflake();
yea you need to add the () to make it work

2021-07-11 15:45 UTC, takos22 requested changes

2021-07-11 15:45 UTC, takos22 commented on cdn/asset.py
> +
why 2 new lines?

2021-07-11 15:45 UTC, takos22 commented on cdn/asset.py
> +        record = await cls.pool.fetchrow(query, name, file_id, creator_id, url_path)
convert file_id and creator_id to int

2021-07-11 15:45 UTC, takos22 commented on cdn/asset.py
> +        return cls(**record)
what happens if the url path already exists?

2021-07-11 15:45 UTC, takos22 commented on cdn/asset.py
> +        return await cls.pool.execute(query, *args)
return none

2021-07-11 15:45 UTC, takos22 commented on cdn/file.py
> +    async def create(cls, name: str, mimetype: str, data: bytes):
type hint pls

2021-07-11 15:45 UTC, takos22 commented on cdn/file.py
> +    mimetype = Column(types.String)
mimetype is after name everywhere so why not here?

2021-07-11 19:01 UTC, SylteA commented on cdn/asset.py
> +
yeah should be 1

2021-07-11 19:01 UTC, SylteA commented on cdn/asset.py
> +        return cls(**record)
L55 would error, but in theory there is a `1` in `390877006486250192896` chance that that happens

2021-07-11 19:01 UTC, SylteA commented on cdn/asset.py
> +        return await cls.pool.execute(query, *args)
Why?
I definitely think that this is the correct solution.

2021-07-11 19:03 UTC, SylteA requested changes

2021-07-11 19:03 UTC, SylteA commented on migrations/0001_init_schema.up.sql
> +    RETURN to_timestamp(((flake >> 22) + 1609459200) / 1000);
Wrong epoch, use the one from create_snowflake()

2021-07-11 19:04 UTC, takos22 commented on cdn/asset.py
> +        return await cls.pool.execute(query, *args)
why would you return anything if its deleted

2021-07-11 20:00 UTC, SylteA commented on cdn/asset.py
> +        return await cls.pool.execute(query, *args)
It returns relevant information whether something was deleted or not

2021-07-12 06:04 UTC, Correct-skill commented on migrations/0001_init_schema.up.sql
> +    RETURN to_timestamp(((flake >> 22) + 1609459200) / 1000);
why is our epoch different in utils.py?

2021-07-12 06:10 UTC, Correct-skill commented
I removed queries cause there is no point in adding them here, its literally unused code...

2021-07-12 06:16 UTC, Correct-skill commented on cdn/asset.py
> +        record = await cls.pool.fetchrow(query, name, file_id, creator_id, url_path)
btw file_id and creator_id are very big integers and it will cause integer overflow in js

2021-07-12 09:01 UTC, SylteA commented on cdn/asset.py
> +        record = await cls.pool.fetchrow(query, name, file_id, creator_id, url_path)
> btw file_id and creator_id are very big integers and it will cause integer overflow in js

Which is why we always select or convert to string before transferring it.
The reasoning behing storing it as a bigint is faster indexing and lower size.

2021-07-12 09:04 UTC, SylteA requested changes

2021-07-12 09:04 UTC, SylteA commented on cdn/asset.py
> +    file: Optional["File"] = None
Remember to include `created_at` property.

2021-07-12 09:04 UTC, SylteA commented on cdn/file.py
> +    data = Column(types.Binary)
Remember to include `created_at` property.

2021-07-12 11:25 UTC, Correct-skill commented
Should be the final commit hopefully 🤞

2021-07-12 15:25 UTC, takos22 commented on cdn/asset.py
> +    file: Optional["File"] = None
This is why we should have a base model or a created_at mixin class

2021-07-12 15:28 UTC, takos22 approved these changes
Looks good to me

2021-07-12 15:28 UTC, takos22 commented on cdn/file.py
> +    def created_at(self) -> "datetime":
You don't need to put datetime in a str

2021-07-12 15:34 UTC, merged