Roles and permissions
Tech-With-Tim/models pull request #5
Opened 2021-08-20 18:41 UTC by mohamed040406

This pr adds role models and permission bases classes along with General permissions and weekly challenge permissions.

2021-08-21 10:17 UTC, takos22 requested changes
You need to fix the `Role.has_permissions`, you should import all the permissions in `permissions/__init__.py` and you should add an `__all__` to the files

2021-08-21 10:17 UTC, takos22 commented on __init__.py
> +from .roles import Role, UserRole
Shouldn't you also import permissions here?

2021-08-21 10:17 UTC, takos22 commented on permissions/bases/category.py
> +
`__all__`

2021-08-21 10:17 UTC, takos22 commented on permissions/bases/permission.py
> +
`__all__`

2021-08-21 10:17 UTC, takos22 commented on permissions/challenges.py
> +
`__all__`

2021-08-21 10:17 UTC, takos22 commented on permissions/bases/category.py
> +    Base class for a permission category
Explain more what is a category, a group of permissions that can be given at the same time? In that case in the Genral permissions category why are you adding admin and manage role perms at the same time?

2021-08-21 10:17 UTC, takos22 commented on permissions/general.py
> +
`__all__`

2021-08-21 10:17 UTC, takos22 commented on roles/role.py
> +
`__all__`

2021-08-21 10:17 UTC, takos22 commented on roles/role.py
> +from ..permissions.general import Administrator
`from ..permissions import Administrator` once you import all the permissions in `permissions/__init__.py`

2021-08-21 10:17 UTC, takos22 commented on roles/role.py
> +            '<Role id="{0.id}" name="{0.name}" '
`name={0.name!r}` instead of `name="{0.name}"` (do that for other attributes too)

2021-08-21 10:17 UTC, takos22 commented on roles/role.py
> +        return self.permissions & permission.value or Administrator().value
Is this parsed as `(self.permissions & permission.value) or Administrator().value`? if so it will always be `True`

2021-08-21 10:17 UTC, takos22 commented on roles/user_role.py
> +        Attributes stored in the `users` table.
``stored in the `userroles` table``

2021-08-21 10:17 UTC, takos22 commented on roles/user_role.py
> +
`__all__`

2021-08-21 10:17 UTC, takos22 commented on roles/user_role.py
> +        return cls(**await cls.pool.execute(query, member_id, role_id))
Separate this into 2 lines, no need to code golf this code 😄
```py
record = await ...
return cls(**record)
```

2021-08-21 10:17 UTC, takos22 commented on roles/user_role.py
> +        return cls(**await cls.pool.execute(query, member_id, role_id))
Separate this into 2 lines, no need to code golf this code 😄
```py
record = await ...
return cls(**record)
```

2021-08-21 10:24 UTC, SylteA requested changes

2021-08-21 10:24 UTC, SylteA commented on permissions/bases/category.py
> +        return perms
This will never be changed in runtime so I think we should use `functools.cached_property`

2021-08-21 10:24 UTC, SylteA commented on permissions/challenges.py
> +    value: int = 1 << 2
`value` attributes shouldn't be shifted.

2021-08-21 10:24 UTC, SylteA commented on roles/role.py
> +                id::TEXT,
This shouldn't be fetching as TEXT, the record is passed to a `Role` object so we want an int.

2021-08-21 10:24 UTC, SylteA commented on roles/role.py
> +    color = Column(types.Integer, default=0x000000)
Shouldn't use black as the default colour, maybe something like 0xFDFDFD

2021-08-21 10:24 UTC, SylteA commented on roles/role.py
> +    async def update(self, **data):
Implement directly on endpoint

2021-08-21 10:24 UTC, SylteA commented on roles/user_role.py
> +    async def create(cls, member_id: int, role_id: int):
Implement directly on endpoint

2021-08-21 10:24 UTC, SylteA commented on roles/user_role.py
> +    async def delete(cls, member_id: int, role_id: int):
Implement directly on endpoint

2021-08-21 10:29 UTC, mohamed040406 commented on permissions/bases/category.py
> +    Base class for a permission category
it is just a group of permissions, doesn't have to be given at the same time

2021-08-24 18:02 UTC, SylteA approved these changes
lgtm

2021-08-24 18:03 UTC, SylteA commented
Could benefit from some database tests directly on the models

2021-08-24 21:08 UTC, takos22 approved these changes
lgtm

2021-08-29 19:18 UTC, SylteA requested changes

2021-08-29 19:18 UTC, SylteA commented on roles/role.py
> +    position = Column(types.Numeric)
Now that we're using the solution with Numeric, could we make this unique?

2021-08-29 19:18 UTC, SylteA commented on roles/role.py
>          """Returns `True` if this Role has all `Permissions`"""
Returns `True` if this role has all provided permissions

2021-08-29 19:18 UTC, SylteA commented on roles/role.py
>          """Returns `True` if this Role has said `Permission`"""
Returns `True` if this role has provided permission

2021-08-31 11:48 UTC, SylteA commented
Also just noticed that migrations haven't been updated to match the new models.

2021-08-31 14:14 UTC, takos22 reviewed
lgtm

2021-08-31 14:14 UTC, takos22 commented on migrations/0001_init_schema.up.sql
> +CREATE TABLE IF NOT EXISTS roles (
Shouldn't you put these in a new migration file?

2021-08-31 17:36 UTC, SylteA approved these changes

2021-08-31 17:37 UTC, merged