Challenges
Tech-With-Tim/models pull request #9
Opened 2021-09-10 20:10 UTC by SylteA

Just a new PR so yall can review.

2021-09-10 20:51 UTC, mohamed040406 requested changes
:)

2021-09-10 20:51 UTC, mohamed040406 commented on challenges/language.py
> +    download_url = Column(types.String)
we said this will be optional, right?

2021-09-10 20:51 UTC, mohamed040406 commented on challenges/language.py
> +        Attributes stored in the `challengeLanguages` table.
wrong table name

2021-09-10 20:51 UTC, mohamed040406 commented on challenges/submission.py
> +        Attributes stored in the `challengeSubmissions` table.
wrong table name

2021-09-10 20:51 UTC, mohamed040406 commented on migrations/0001_init_schema.down.sql
> +DROP TABLE IF EXISTS userrules RESTRICT;
?

2021-09-10 20:51 UTC, mohamed040406 commented on migrations/0001_init_schema.up.sql
> +    language_id BIGINT REFERENCES challengeLanguages(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT NULL,
wrong table name

2021-09-10 20:51 UTC, mohamed040406 commented on migrations/0001_init_schema.up.sql
> +    download_url TEXT NOT NULL,
we said this will be optional, right?

2021-09-10 20:51 UTC, mohamed040406 commented on challenges/submission.py
> +        types.ForeignKey("challengeLanguages", "id", sql_type=types.Integer(big=True))
wrong table name

2021-09-10 20:53 UTC, mohamed040406 commented on migrations/0001_init_schema.up.sql
>      author_id BIGINT REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT NULL,
why not a relation to `challengeparticipants`?

2021-09-10 21:48 UTC, takos22 commented on challenges/challenge.py
> +        :param str description:                 The challenge description.
Maybe you should divide this into multiple fields like: intro, task, examples, rules...

2021-09-10 21:48 UTC, takos22 commented on challenges/language.py
> +    download_url = Column(types.String)
`nullable=True` <:ugundu:844094529829076992>

2021-09-11 07:25 UTC, SylteA commented on migrations/0001_init_schema.up.sql
>      author_id BIGINT REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION NOT NULL,
You have author_id

2021-09-11 07:26 UTC, SylteA commented on challenges/challenge.py
> +        :param str description:                 The challenge description.
I think description is enough for introduction and task.
Will add example.

We won't have rules.

2021-09-11 07:30 UTC, SylteA commented on challenges/challenge.py
> +        :param str description:                 The challenge description.
As we're moving to piston to support more languages I don't see us needing a example, if we do we can add it to description temporarily.
Instead of the previous 
```python
def submission(inp):
    ...
    return solution
```

We will now have
```python
inp = input()
...
print(solution)
```

2021-09-11 07:38 UTC, takos22 commented on challenges/challenge.py
> +        :param str description:                 The challenge description.
It’s not example code, but example input and output strings

2021-09-11 07:41 UTC, SylteA commented on challenges/challenge.py
> +        :param str description:                 The challenge description.
> It’s not example code, but example input and output strings

So 
```py
example_in: Array(String)
example_out: Array(String)
```

2021-09-11 09:16 UTC, takos22 approved these changes
Looks good to me

2021-09-11 11:09 UTC, mohamed040406 requested changes

2021-09-11 11:09 UTC, mohamed040406 commented on challenges/submission.py
> +    )
this should be replaced by a relation to `challengeparticipants`

2021-09-11 11:37 UTC, SylteA commented on challenges/submission.py
> +    )
> this should be replaced by a relation to `challengeparticipants`

Why? I don't agreed.

The submission was made by that user, you can get the participant through the user id.
If anything you should have a submission_id fkey on participants, but all of these are accessible through the user id.

2021-09-11 12:31 UTC, Shubhaankar-Sharma commented on challenges/submission.py
> +    )
so basically we will bloat the user table with all the submissions till date, rather than doing `select * from submissions where user_id=?` ?

2021-09-11 12:32 UTC, Shubhaankar-Sharma commented on challenges/submission.py
> +    )
i think it should be replaced by a relation to challengeparticipants, since we won't have to add extra checks to check if the user is in the challenge

2021-09-12 14:09 UTC, SylteA commented on challenges/submission.py
> +    )
The extra 8 bits of data required on `challengesubmissions` is well worth it in comparison to the query speed we loose on other operations.
The most common operations on submissions would be **fetch by user** / **fetch by challenge**, having each of those queries have to go through `challengeparticipants` is not worth it.

2021-09-12 15:05 UTC, mohamed040406 approved these changes

2021-09-12 15:19 UTC, takos22 commented on migrations/0001_init_schema.up.sql
> +    id BIGINT UNIQUE NOT NULL,
If it's unique here, why isn't it unique on every other id column?

2021-09-12 15:21 UTC, SylteA commented on migrations/0001_init_schema.up.sql
> +    id BIGINT UNIQUE NOT NULL,
> If it's unique here, why isn't it unique on every other id column

Because it's normally a primary key.

2021-09-12 15:25 UTC, takos22 commented on migrations/0001_init_schema.up.sql
> +    id BIGINT UNIQUE NOT NULL,
Then why isn't it a primary key here?

2021-09-12 15:27 UTC, takos22 commented on migrations/0001_init_schema.up.sql
> +    id BIGINT UNIQUE NOT NULL,
Never mind I just saw the pk was on other columns

2021-09-12 15:27 UTC, SylteA commented on migrations/0001_init_schema.up.sql
> +    id BIGINT UNIQUE NOT NULL,
The primary key on this table is `(challenge_id, author_id)`, this is to make each row unique on these columns.
The `UNIQUE` keyword only works on individual columns.

2021-09-12 15:37 UTC, SylteA commented
Having titles unique is so we can use titles as slugs instead of the ID.
The API will need to account for this.

2021-09-12 16:03 UTC, takos22 commented
> Having titles unique is so we can use titles as slugs instead of the ID.
> The API will need to account for this.

Why not make a slug column with all lowercase, dash separated words and the title with the good case and spaces? It would make more sense because we could then use the slug in the url

2021-09-12 20:25 UTC, SylteA commented
> > Having titles unique is so we can use titles as slugs instead of the ID.
> > The API will need to account for this.
> 
> Why not make a slug column with all lowercase, dash separated words and the title with the good case and spaces? It would make more sense because we could then use the slug in the url

Was thinking we'd just use title.lower()

2021-09-13 17:50 UTC, takos22 commented on challenges/challenge.py
> +    title = Column(types.String, unique=True)
Now that there's the slug, the title could be not unique I think, even though it should be avoided

2021-09-13 17:57 UTC, SylteA commented on challenges/challenge.py
> +    title = Column(types.String, unique=True)
> Now that there's the slug, the title could be not unique I think, even though it should be avoided

Title should still be unique as it's a keyword you can search by.
Compare it to the tag titles

2021-09-13 19:22 UTC, merged